"""Generate a checked-in ABI manifest from the actual Logos declarations."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def abi_kind(type_name):
    value = re.sub(r'__unsafe_unretained|__strong|__weak|_Nullable|_Nonnull', '', type_name)
    value = re.sub(r'\s+', '', value)
    primitives = {'void': 'v', 'BOOL': 'boolean', '_Bool': 'boolean',
                  'NSInteger': 'q', 'NSUInteger': 'Q', 'longlong': 'q',
                  'unsignedlonglong': 'Q', 'unsignedint': 'I', 'CGFloat': 'd',
                  'double': 'd', 'UIFontWeight': 'd', 'UIAlertActionStyle': 'q',
                  'UIViewContentMode': 'q', 'SEL': ':', 'NSNotificationName': '@',
                  'CGPoint': '{CGPoint=', 'CGSize': '{CGSize='}
    if value in primitives:
        return primitives[value]
    if value.endswith('**'):
        return '^@'
    if value.startswith('id') or value.endswith('*') or '(^)' in value:
        return '@'
    raise ValueError(f'Unhandled hook ABI type: {type_name}')


def manifest():
    entries = {}
    for path in sorted((ROOT / 'src/Hooks').glob('*.x')):
        for cls, body in re.findall(r'%hook\s+(\w+)(.*?)(?=%end)', path.read_text(), re.S):
            for sign, result, signature in re.findall(r'^([-+])\s*\(([^)]+)\)\s*([^;{]+)\{', body, re.M):
                cursor, parts, arguments = 0, [], []
                while True:
                    found = re.search(r'(\w+)\s*:\s*\(', signature[cursor:])
                    if not found:
                        break
                    parts.append(found.group(1) + ':')
                    start = cursor + found.end()
                    position, depth = start, 1
                    while depth and position < len(signature):
                        if signature[position] == '(': depth += 1
                        if signature[position] == ')': depth -= 1
                        position += 1
                    assert depth == 0, signature
                    arguments.append(abi_kind(signature[start:position - 1]))
                    cursor = position
                selector = ''.join(parts) if parts else signature.strip().split()[0]
                key = (cls, sign, selector)
                entry = (abi_kind(result), tuple(arguments))
                if key in entries:
                    assert entries[key] == entry, f'Conflicting hook signature: {key}'
                entries[key] = entry
    return entries


def render():
    lines = ['// Generated by scripts/hook_abi.py; verified against every v7 Logos declaration.',
             'typedef struct {',
             '    const char *className, *selector, *returnKind;',
             '    BOOL classMethod;',
             '    unsigned int argumentCount;',
             '    const char *arguments[12];',
             '} NFBHookABI;',
             'static const NFBHookABI NFBHookABIs[] = {']
    for (cls, sign, selector), (result, args) in sorted(manifest().items()):
        arguments = ', '.join('"' + value + '"' for value in args) or 'NULL'
        lines.append('    {"%s", "%s", "%s", %s, %d, {%s}},' %
                     (cls, selector, result, 'YES' if sign == '+' else 'NO', len(args), arguments))
    lines += ['};', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    print(render(), end='')
